[tool.ruff]
target-version = "py312"
line-length = 100
extend-exclude = [
    "*/migrations/*",
    "static/*",
    "staticfiles/*",
    "media/*",
    "backups/*",
]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM", "C4"]
ignore = ["E203", "E266", "E501", "W503"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
